### ISSUE TITLE
[FEAT] Option for putting remote instances in a folder

### ISSUE THREAD

**Issue by filiptibell** [red-blox/zap#130]
We have some wally packages such as these, that we use internally:
- Character animation (replicated headtracking, hand/arm ik, etc)
- Interactables (proximity prompts with extras like better seat handling, also has custom replication)
- Physics package (better network ownership, with actions and low-cost replication to clients)
and some others, but these are the important ones.

I'd like to migrate each individual package to use Zap for optimized networking, but I dont want to delegate all the remote definitions and handling to the consumers of these packages (games). 
Right now each package can use the `remote_scope` option, and migrating to zap will ***work***, but it means we'll have a lot of remotes directly in ReplicatedStorage. That indirectly means:
- Finding instances whenever ReplicatedStorage is opened is more difficult
- IDE autocomplete for instances under ReplicatedStorage gets cluttered

It would be nice to have a `remote_folder` setting, or something similar, where as long as all packages use the same option value, all remotes will be under this one folder. It doesn't need to support nesting or anything fancy, a single folder is fine.

**Comment by sasial-dev** [comment]
Completed in https://github.com/red-blox/zap/commit/523d15f0f73f7af260c49889ba26b7168525fbc7
