### ISSUE TITLE
[BUG] Tooling missing CFrameSpecialCases

### ISSUE THREAD

**Issue by Ezzenix** [red-blox/zap#133]
## Describe the bug
The file generated when you have the tooling option enabled is missing the CFrameSpecialCases variable.

## Reproduction
[Playground](https://zap.redblox.dev/playground.html?code=b3B0IHRvb2xpbmcgPSB0cnVlDQoNCmV2ZW50IFNoYWRlc1JvbGxlZCA9IHsNCglmcm9tOiBTZXJ2ZXIsDQoJdHlwZTogVW5yZWxpYWJsZSwNCgljYWxsOiBNYW55QXN5bmMsDQoJZGF0YTogQWxpZ25lZENGcmFtZQ0KfQ==)

## Expected behavior
CFrameSpecialCases should exist so the tooling script doesn't error.

**Comment by sasial-dev** [comment]
I'm so sorry - I forgot to release this!

**Comment by sasial-dev** [comment]
It will be out in `v0.6.14` momentarily.
