### ISSUE TITLE
[BUG] des ranges aren't max inclusive

### ISSUE THREAD

**Issue by As8D** [red-blox/zap#18]
## Describe the bug
Ranges aren't max inclusive, the value is 1, but it's checking if it's < 1

## Reproduction
Link to playground with accurate reproduction
https://zap.redblox.dev/playground.html?code=ZXZlbnQgcm91bmQgPSB7Cglmcm9tOiBTZXJ2ZXIsCgl0eXBlOiBSZWxpYWJsZSwKCWNhbGw6IFNpbmdsZVN5bmMsCglkYXRhOiBTdHJpbmdbNF0KfQoKZXZlbnQgY29tbWFuZCA9IHsKCWZyb206IENsaWVudCwKCXR5cGU6IFVucmVsaWFibGUsCgljYWxsOiBTaW5nbGVTeW5jLAoJZGF0YTogewoJCWRlbHRhVGltZTogZjMyLAoJCVg6IGk4ICgtMS4uMSksCgkJWjogaTggKC0xLi4xKQoJfSwKfQo=

## Expected behavior
That ranges _are_ max inclusive, so that this bug doesn't happen

**Comment by sasial-dev** [comment]
This issue was fixed in #16, and I tested that it works correctly on master.
