### ISSUE TITLE
[FEAT] Remove shadowing variable redefinitions

### ISSUE THREAD

**Issue by noahrepublic** [red-blox/zap#23]
## Describe your feature
Selene goes wild due to lots of 'shadowing variable' 

## Implementation Details
You could silence selene, however keeping track of what is already defined shouldn't be too hard in Codegen

**Comment by jackdotink** [comment]
This is similar to #22 in that it resolves issues with linters. This is low priority and the easiest solution is to disable linters with a comment, which we'll do in 0.3.

**Comment by sasial-dev** [comment]
We've gone ahead and silenced the linters in `0.3.1`. Please note that I'll keep this issue open to remove shadowing down the line - but as @jackdotink mentioned it is low priority.

**Comment by sasial-dev** [comment]
The actual bug of zap shadowing should've been fixed in `0.6.3`. If that doesn't make selene happy please just reopen this issue.
