### ISSUE TITLE
[FEAT] Clarify output FS errors

### ISSUE THREAD

**Issue by Crystalflxme** [red-blox/zap#24]
## Describe your feature
While using the CLI, you can run into filesystem errors which don't clearly describe what the issue is.

These error messages should be more descriptive, pointing users to solutions. As a quality of life feature for output directories, any nonexistent directories should be created during execution.

### Examples
For instance, a config that looks like this
```
opt output_client = ./network/client.luau
opt output_server = ./network/server.luau
```
...will cause the following generic and unclear filesystem error on Windows if no `./network` directory exists:
```
Error: The system cannot find the path specified. (os error 3)
```

A similar error,
```
Error: The system cannot find the file specified. (os error 2)
```
...is output if the path provided to the config file is invalid.

## Alternatives
Both of these are minor issues, so creating the directories in question and/or ensuring file paths are correct both work. The docs could also cover these common mistakes.

**Comment by jackdotink** [comment]
This issue will be addressed in the 0.3 release.
