### ISSUE TITLE
[FEAT] Support for CFrames

### ISSUE THREAD

**Issue by sasial-dev** [red-blox/zap#28]
## Describe your feature
Zap should support the `CFrame` datatype.

## Alternatives
The alternative is not supporting CFrames.

## Implementation Details
The slowest way we can impliment it is by sending `i32[12]` from `CFrame:GetComponents`. This is expensive and wastes network bandwidth.

The challenge with CFrames is that Roblox uses *a lot* of compression methods for sending CFrames. We also should do this - we just need to research how it is done to avoid sending 12 `i32`s.

**Comment by jackdotink** [comment]
A good resource for this will be https://github.com/Pyseph/RemotePacketSizeCounter, which has all the different CFrame variations and how large they are.

**Comment by sasial-dev** [comment]
We should base it off the roblox binary format - see https://dom.rojo.space/binary.html#cframe for more details.
