### ISSUE TITLE
[FEAT] Roblox-ts Type generation

### ISSUE THREAD

**Issue by MojaveMF** [red-blox/zap#68]
Add a flag that can be added to the compile such as `--roblox-ts` or opt you could add to enable it.
This would not require to rewrite the already existing code generation and would generate a <outputName>.d.ts in the output location as well.

If you aren't apposed to the feature but don't feel like developing it i am more than happy to fork it and create a pull request.

Here is an example

```zap
event Test = {
    from: Server,
    type: Reliable,
    call: ManyAsync,
    data: struct {
        foo: u32,
        bar: string,
    },
}
```
Would generate something like this on the client
```ts
type Test = {
    foo: number;
    bar: string;
};

type Callback<T extends {}> = (value: T) => void;

interface ClientEvent<T extends {}> {
    On: (cb: Callback<T>) => void;
}

interface Generated {
    Test: ClientEvent<Test>;
}

declare const Exports: Generated;

export = Exports;
```

**Comment by MojaveMF** [comment]
I forgot to make it return an unlistener in the types but you get the idea

**Comment by jackdotink** [comment]
this already exists under the `typescript` opt

**Comment by MojaveMF** [comment]
> this already exists under the `typescript` opt

mb didn't see it
