### ISSUE TITLE
[BUG] TypeScript type generation should use semicolons

### ISSUE THREAD

**Issue by osyrisrblx** [red-blox/zap#70]
## Describe the bug
Given an input like
```
opt typescript = true

event MyEvent = {
	from: Server,
	type: Reliable,
	call: ManyAsync,
	data: u8,
}
```

Zap will generate
```ts
// Server generated by Zap v0.6.1 (https://github.com/red-blox/zap)
export const MyEvent: {
	Fire: (Player: Player, Value: number) => void
	FireAll: (Value: number) => void
	FireExcept: (Except: Player, Value: number) => void
	FireList: (List: Player[], Value: number) => void
};
```

But TypeScript style usually dictates that object types should use semicolons like:
```ts
export const MyEvent: {
	Fire: (Player: Player, Value: number) => void;
	FireAll: (Value: number) => void;
	FireExcept: (Except: Player, Value: number) => void;
	FireList: (List: Player[], Value: number) => void;
};
```

Technically, this is a stylistic thing and not required.. but it will trigger common lint warnings.

## Reproduction
[playground link](https://zap.redblox.dev/playground.html?code=b3B0IHR5cGVzY3JpcHQgPSB0cnVlCgpldmVudCBNeUV2ZW50ID0gewoJZnJvbTogU2VydmVyLAoJdHlwZTogUmVsaWFibGUsCgljYWxsOiBNYW55QXN5bmMsCglkYXRhOiB1OCwKfQ==)

## Expected behavior
TypeScript type generation should properly use semicolons.

**Comment by sasial-dev** [comment]
FIxed in #94
