### ISSUE TITLE
[FEAT] Vector2 class support

### ISSUE THREAD

**Issue by Blueeyy** [red-blox/zap#78]
## Describe your feature
Support for the Vector2 class; this is more of a personal need so I apologize in advance. I use Zap for voxel replication and I only need to save 2 values instead of 3.

**Comment by jackdotink** [comment]
For transparency here zap will never support the Vector2 class, but will instead support Vector3's with two values. This is due to luau heap-allocating Vector2's and stack-allocating Vector3's. This means they have a dramatic performance difference.
