### ISSUE TITLE
[BUG] `unknown` typed as `unknown?`

### ISSUE THREAD

**Issue by nezuo** [red-blox/zap#88]
## Describe the bug
Using `unknown` results in `unknown?`:
![image](https://github.com/red-blox/zap/assets/48431591/7dca4c58-b766-4a48-b721-67753dccd1ab)

## Reproduction
https://zap.redblox.dev/playground.html?code=ZXZlbnQgdmFsdWUgPSB7DQogICAgZnJvbTogU2VydmVyLA0KICAgIHR5cGU6IFJlbGlhYmxlLA0KICAgIGNhbGw6IFNpbmdsZVN5bmMsDQogICAgZGF0YTogdW5rbm93biwNCn0NCg==

**Comment by sasial-dev** [comment]
‘unknown’ being optional is valid behaviour. But it should not appear like that in types.
